language: node_js
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
node_js:
  - '6'
  - '7'
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm run build
script:
  - npm run lint
  - npm run test